-- local tele = require('telescope')
-- tele.load_extension('project')
-- require'telescope'.extensions.project.project{ display_type = 'full' }

-- tele.setup({
-- 	extensions = {
-- 		project = {
-- 			base_dirs = {
-- 				{path = "~/.config/nvim"},
-- 				{path = "~/Projects/UCL/SymPepo"}
-- 			}
-- 		},
-- 		display_type = 'full'
-- 	}
-- })
